name: First GitHub Action

on:
  push:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a Hello Message
        run: echo "✅ Hello Harshada! Your GitHub Action is working!"
